# Generated by Django 5.0.4 on 2024-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
